### ISSUE TITLE
running ssl with zeus and puma

### ISSUE THREAD

**Issue by exocode** [burke/zeus#487]
Normally I start my zeus server, which starts my puma server also.

I do this like this:

```
puma -b 'ssl://127.0.0.1:3000?key=/Users/jan/.ssh/server.key&cert=/Users/jan/.ssh/server.crt'
```

**How can I start zeus to force puma to run in https.**

**Comment by joelvh** [comment]
Hi @latortuga I realize this is old... the issue is described in https://github.com/rails/rails/issues/25700, which is that `rails server` overrides the custom puma configuration and doesn't bind SSL. Any thoughts on how to create something like `zeus puma`?

@exocode you can get it to work with a custom plan, and don't specify the port as an argument to `puma`, but rather pass it in to foreman or set the environment variable.

```ruby
require 'zeus/rails'

class ZeusPlan < Zeus::Rails
  def puma_environment
    require 'puma/cli'
  end

  def puma(argv=ARGV)
    Puma::CLI.new(argv.dup).run
  end
end

Zeus.plan = ZeusPlan.new
```

```javascript
{
  "command": "ruby -rubygems -r./zeus_plan -eZeus.go",

  "plan": {
    "boot": {
      "default_bundle": {
        "development_environment": {
          "server": ["s"],
          "console": ["c"],
          "dbconsole": [],
          "rake": []
        },
        "puma_environment": {
          "puma": []
        }
      }
    }
  }
}
```

And then `zeus puma -C config/puma.rb`

Or setup a `foreman` `Procfile` with the following:

```bash
zeus: echo "Spawining Zeus..." && zeus start
web: sleep 2 && zeus puma -C config/puma.rb
```
